# Generated by Django 5.0.1 on 2025-11-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("OFFICIAL", "Official Government"),
                            ("SENSOR", "Community Sensors"),
                            ("MODEL", "Atmospheric Model"),
                            ("AGGREGATOR", "Data Aggregator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("api_endpoint", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_api_key", models.BooleanField(default=True)),
                ("countries_covered", models.JSONField(default=list)),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                ("default_trust_weight", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AQICategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        choices=[("EPA", "EPA AQI (US)"), ("AQHI", "AQHI (Canada)")],
                        default="EPA",
                        max_length=10,
                    ),
                ),
                ("min_value", models.IntegerField()),
                ("max_value", models.IntegerField()),
                ("category", models.CharField(max_length=50)),
                ("color_hex", models.CharField(max_length=7)),
                ("health_message", models.TextField()),
                ("sensitive_groups", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "AQI Category",
                "verbose_name_plural": "AQI Categories",
                "ordering": ["scale", "min_value"],
                "indexes": [
                    models.Index(
                        fields=["scale", "min_value", "max_value"],
                        name="core_aqicat_scale_b822e0_idx",
                    )
                ],
            },
        ),
    ]
