# Generated by Django 5.0.1 on 2025-11-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AggregatedForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lat",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "lon",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("forecast_timestamp", models.DateTimeField(db_index=True)),
                ("aqi", models.IntegerField()),
                ("category", models.CharField(max_length=50)),
                ("pollutants", models.JSONField(default=dict)),
                ("sources", models.JSONField(default=list)),
                ("source_count", models.IntegerField(default=0)),
                ("cached_until", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Aggregated Forecast",
                "verbose_name_plural": "Aggregated Forecasts",
                "ordering": ["forecast_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["lat", "lon", "forecast_timestamp"],
                        name="forecast_ag_lat_9952c6_idx",
                    ),
                    models.Index(
                        fields=["cached_until"], name="forecast_ag_cached__c7c961_idx"
                    ),
                ],
                "unique_together": {("lat", "lon", "forecast_timestamp")},
            },
        ),
        migrations.CreateModel(
            name="ForecastData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lat",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "lon",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("forecast_timestamp", models.DateTimeField(db_index=True)),
                ("aqi", models.IntegerField()),
                ("category", models.CharField(blank=True, max_length=50)),
                ("pollutants", models.JSONField(default=dict)),
                ("source", models.CharField(db_index=True, max_length=50)),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Forecast Data",
                "verbose_name_plural": "Forecast Data",
                "ordering": ["forecast_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["lat", "lon", "forecast_timestamp"],
                        name="forecast_fo_lat_598fe8_idx",
                    ),
                    models.Index(
                        fields=["source", "forecast_timestamp"],
                        name="forecast_fo_source_9e68eb_idx",
                    ),
                    models.Index(
                        fields=["-generated_at"], name="forecast_fo_generat_907254_idx"
                    ),
                ],
            },
        ),
    ]
