# Generated by Django 5.0.1 on 2025-11-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(db_index=True, max_length=2, unique=True),
                ),
                ("country_name", models.CharField(max_length=100)),
                ("source_priority", models.JSONField(default=list)),
                (
                    "default_aqi_scale",
                    models.CharField(
                        choices=[("EPA", "EPA AQI"), ("AQHI", "AQHI")],
                        default="EPA",
                        max_length=10,
                    ),
                ),
                ("has_official_data", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Region Configuration",
                "verbose_name_plural": "Region Configurations",
                "ordering": ["country_name"],
            },
        ),
        migrations.CreateModel(
            name="LocationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lat",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "lon",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(db_index=True, max_length=2)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("formatted_address", models.TextField(blank=True)),
                ("cached_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("hit_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Location Cache",
                "verbose_name_plural": "Location Cache Entries",
                "indexes": [
                    models.Index(
                        fields=["lat", "lon"], name="location_lo_lat_73bacd_idx"
                    ),
                    models.Index(
                        fields=["country"], name="location_lo_country_6acbc1_idx"
                    ),
                    models.Index(
                        fields=["cached_at"], name="location_lo_cached__3610ba_idx"
                    ),
                ],
                "unique_together": {("lat", "lon")},
            },
        ),
    ]
