# Generated by Django 5.0.1 on 2025-11-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdapterStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("total_requests", models.IntegerField(default=0)),
                ("total_failures", models.IntegerField(default=0)),
                ("requests_this_minute", models.IntegerField(default=0)),
                ("minute_window_start", models.DateTimeField(blank=True, null=True)),
                ("status_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Adapter Status",
                "verbose_name_plural": "Adapter Statuses",
                "ordering": ["source"],
            },
        ),
        migrations.CreateModel(
            name="RawAPIResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(db_index=True, max_length=50)),
                ("endpoint", models.CharField(max_length=200)),
                ("params", models.JSONField(default=dict)),
                ("response_data", models.JSONField()),
                ("status_code", models.IntegerField()),
                ("response_time_ms", models.IntegerField(null=True)),
                ("is_error", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Raw API Response",
                "verbose_name_plural": "Raw API Responses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-created_at"],
                        name="adapters_ra_source_953e45_idx",
                    ),
                    models.Index(
                        fields=["is_error"], name="adapters_ra_is_erro_993b1f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(db_index=True, max_length=50)),
                (
                    "lat",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "lon",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("aqi", models.IntegerField(blank=True, null=True)),
                ("aqi_category", models.CharField(blank=True, max_length=50)),
                ("pollutants", models.JSONField(default=dict)),
                (
                    "quality_level",
                    models.CharField(
                        choices=[
                            ("verified", "Verified Station Data"),
                            ("model", "Atmospheric Model"),
                            ("sensor", "Community Sensor"),
                            ("estimated", "Estimated/Interpolated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("station_id", models.CharField(blank=True, max_length=100)),
                ("station_name", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Source Data",
                "verbose_name_plural": "Source Data",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["source", "timestamp"],
                        name="adapters_so_source_c03329_idx",
                    ),
                    models.Index(
                        fields=["lat", "lon", "timestamp"],
                        name="adapters_so_lat_c865ff_idx",
                    ),
                    models.Index(
                        fields=["quality_level"], name="adapters_so_quality_06242c_idx"
                    ),
                ],
            },
        ),
    ]
