# Generated by Django 5.0.1 on 2025-11-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlendedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lat",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "lon",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("current_aqi", models.IntegerField()),
                ("category", models.CharField(max_length=50)),
                ("pollutants", models.JSONField(default=dict)),
                ("sources", models.JSONField(default=list)),
                ("source_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("cached_until", models.DateTimeField(db_index=True)),
                ("hit_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Blended Data",
                "verbose_name_plural": "Blended Data",
                "indexes": [
                    models.Index(
                        fields=["lat", "lon"], name="fusion_blen_lat_97dc79_idx"
                    ),
                    models.Index(
                        fields=["cached_until"], name="fusion_blen_cached__5f807f_idx"
                    ),
                    models.Index(
                        fields=["-last_updated"], name="fusion_blen_last_up_852f67_idx"
                    ),
                ],
                "unique_together": {("lat", "lon")},
            },
        ),
        migrations.CreateModel(
            name="FusionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("query_lon", models.DecimalField(decimal_places=6, max_digits=9)),
                ("result_aqi", models.IntegerField(null=True)),
                ("sources_used", models.JSONField(default=list)),
                ("sources_attempted", models.JSONField(default=list)),
                ("sources_failed", models.JSONField(default=list)),
                ("fusion_method", models.CharField(max_length=50)),
                ("weight_details", models.JSONField(default=dict)),
                ("execution_time_ms", models.IntegerField(null=True)),
                ("cache_hit", models.BooleanField(default=False)),
                ("has_error", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Fusion Log",
                "verbose_name_plural": "Fusion Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="fusion_fusi_created_08ff67_idx"
                    ),
                    models.Index(
                        fields=["has_error"], name="fusion_fusi_has_err_cf0043_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_code", models.CharField(db_index=True, max_length=50)),
                (
                    "region_code",
                    models.CharField(db_index=True, default="DEFAULT", max_length=10),
                ),
                ("trust_weight", models.FloatField(default=1.0)),
                ("priority_rank", models.IntegerField(default=5)),
                ("distance_weight_factor", models.FloatField(default=1.0)),
                ("time_decay_factor", models.FloatField(default=1.0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Source Weight",
                "verbose_name_plural": "Source Weights",
                "ordering": ["region_code", "priority_rank"],
                "indexes": [
                    models.Index(
                        fields=["region_code", "priority_rank"],
                        name="fusion_sour_region__bff021_idx",
                    )
                ],
                "unique_together": {("source_code", "region_code")},
            },
        ),
    ]
